/**
 * TM Sweets & Artisanal Chocolatier - Master Catalog
 * Featuring Royal Indian & European Fusion Sweets, Single-Origin Chocolates, and Luxury Gift Vaults.
 */

const CHOCOLATE_PRODUCTS = [
  // 1. TM Royal Heritage & Fusion Sweets
  {
    id: "tm-sweet-01",
    name: "TM 24K Pure Gold Leaf Kaju Katli",
    category: "royal-sweets",
    categoryLabel: "TM Royal Sweets",
    price: 18.00,
    originalPrice: 22.00,
    rating: 5.0,
    reviewsCount: 380,
    cocoaPercentage: 0,
    origin: "TM Royal Kitchens (Heritage)",
    flag: "👑",
    badge: "TM Signature",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&w=800&q=80",
    description: "Our crowning heritage confection: Grade-A Goan cashews stone-ground with organic saffron and enveloped in genuine edible 24-karat gold leaf.",
    tastingNotes: ["Melt-in-Mouth Cashew", "Kashmiri Saffron", "Cardamom Nectar", "24K Gold"],
    weight: "250g / 8.8 oz",
    dietary: ["Vegetarian", "Gluten-Free", "Royal Heritage"],
    stock: 40,
    featured: true
  },
  {
    id: "tm-sweet-02",
    name: "TM Chocolate Enrobed Ghee Mysore Pak",
    category: "royal-sweets",
    categoryLabel: "TM Royal Sweets",
    price: 16.50,
    originalPrice: 20.00,
    rating: 4.9,
    reviewsCount: 295,
    cocoaPercentage: 55,
    origin: "TM Artisanal Workshop",
    flag: "✨",
    badge: "Bestseller",
    image: "https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-decadent traditional pure cow ghee Mysore Pak dipped in 55% Venezuelan dark chocolate. A legendary melt with a crisp chocolate snap.",
    tastingNotes: ["Pure Desi Ghee", "Caramelized Besan", "Velvet Dark Chocolate", "Nutty Crisp"],
    weight: "220g / 7.7 oz",
    dietary: ["Vegetarian", "Gluten-Free"],
    stock: 35,
    featured: true
  },
  {
    id: "tm-sweet-03",
    name: "TM Royal Cashew Pistachio Saffron Roll",
    category: "royal-sweets",
    categoryLabel: "TM Royal Sweets",
    price: 19.50,
    originalPrice: 24.00,
    rating: 4.9,
    reviewsCount: 215,
    cocoaPercentage: 0,
    origin: "TM Confectionery Studio",
    flag: "👑",
    badge: "Master Selection",
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80",
    description: "Slow-conched cashew dough swirled with emerald Iranian pistachios, crushed almonds, and infused with wild organic saffron honey.",
    tastingNotes: ["Iranian Pistachio", "Cashew Cream", "Rose Honey", "Kashmir Saffron"],
    weight: "300g / 10.5 oz",
    dietary: ["Vegetarian", "Gluten-Free", "Royal Selection"],
    stock: 28,
    featured: true
  },

  // 2. TM Single-Origin Dark Chocolates
  {
    id: "tm-dark-01",
    name: "TM Ecuadorian Arriba Nacional 85%",
    category: "dark",
    categoryLabel: "Dark Chocolate",
    price: 14.50,
    originalPrice: 18.00,
    rating: 4.9,
    reviewsCount: 142,
    cocoaPercentage: 85,
    origin: "Ecuador (Los Ríos)",
    flag: "🇪🇨",
    badge: "Single Origin",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
    description: "Pure heirloom Arriba Nacional cacao boasting delicate floral aromas, toasted blackberry, and deep earthy truffle undertones.",
    tastingNotes: ["Blackberry", "Jasmine", "Roasted Walnut", "Smoked Oak"],
    weight: "100g / 3.5 oz",
    dietary: ["Vegan", "Organic", "Single-Origin", "Gluten-Free"],
    stock: 24,
    featured: true
  },
  {
    id: "tm-dark-02",
    name: "TM Madagascar Sambirano Valley 72%",
    category: "dark",
    categoryLabel: "Dark Chocolate",
    price: 13.00,
    originalPrice: 15.50,
    rating: 4.8,
    reviewsCount: 98,
    cocoaPercentage: 72,
    origin: "Madagascar",
    flag: "🇲🇬",
    badge: "Single Origin",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=800&q=80",
    description: "Vibrant and citrusy dark chocolate with raspberry high notes, sparkling acidity, and a creamy, lingering cocoa finish.",
    tastingNotes: ["Raspberry", "Red Currant", "Citrus Zest", "Caramelized Cacao"],
    weight: "90g / 3.2 oz",
    dietary: ["Vegan", "Single-Origin", "Gluten-Free"],
    stock: 18,
    featured: false
  },
  {
    id: "tm-dark-03",
    name: "TM Noir Intense 90% Grand Cru",
    category: "dark",
    categoryLabel: "Dark Chocolate",
    price: 15.00,
    originalPrice: 17.50,
    rating: 4.7,
    reviewsCount: 76,
    cocoaPercentage: 90,
    origin: "Venezuela (Carenero)",
    flag: "🇻🇪",
    badge: "High Cacao",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    description: "For the purist: an uncompromising 90% dark chocolate with notes of espresso crema, dark roasted cacao, and tobacco leaf.",
    tastingNotes: ["Espresso Crema", "Dark Plum", "Tobacco Leaf", "Nutmeg"],
    weight: "100g / 3.5 oz",
    dietary: ["Vegan", "Sugar-Conscious", "Organic", "Single-Origin"],
    stock: 15,
    featured: false
  },

  // 3. TM Alpine & Caramel Milk Chocolates
  {
    id: "tm-milk-01",
    name: "TM Swiss Alpine Meadow Milk 45%",
    category: "milk",
    categoryLabel: "Milk Chocolate",
    price: 12.00,
    originalPrice: 14.00,
    rating: 4.9,
    reviewsCount: 210,
    cocoaPercentage: 45,
    origin: "Switzerland (Bernese Oberland)",
    flag: "🇨🇭",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1587132137056-bfbf0166836e?auto=format&fit=crop&w=800&q=80",
    description: "Crafted with pure Swiss alpine pasture milk and caramelized honey notes. Velvet smooth with a melt-in-the-mouth texture.",
    tastingNotes: ["Malted Milk", "Heather Honey", "Butterscotch", "Tahitian Vanilla"],
    weight: "100g / 3.5 oz",
    dietary: ["Vegetarian", "Gluten-Free"],
    stock: 35,
    featured: true
  },
  {
    id: "tm-milk-02",
    name: "TM Belgian Fleur de Sel Salted Caramel Milk",
    category: "milk",
    categoryLabel: "Milk Chocolate",
    price: 13.50,
    originalPrice: 16.00,
    rating: 5.0,
    reviewsCount: 312,
    cocoaPercentage: 42,
    origin: "Belgium (Bruges)",
    flag: "🇧🇪",
    badge: "Award Winner",
    image: "https://images.unsplash.com/photo-1526081347589-7fa3cb41b4b2?auto=format&fit=crop&w=800&q=80",
    description: "Rich Belgian milk chocolate studded with handcrafted crunchy butter caramel and genuine Guérande fleur de sel crystals.",
    tastingNotes: ["Salted Caramel", "Brown Butter", "Toffee Crisp", "Creamy Cocoa"],
    weight: "100g / 3.5 oz",
    dietary: ["Vegetarian"],
    stock: 42,
    featured: true
  },
  {
    id: "tm-milk-03",
    name: "TM Piedmont Hazelnut Gianduja Silk",
    category: "milk",
    categoryLabel: "Milk Chocolate",
    price: 16.00,
    originalPrice: 19.00,
    rating: 4.9,
    reviewsCount: 185,
    cocoaPercentage: 38,
    origin: "Italy (Turin)",
    flag: "🇮🇹",
    badge: "Artisanal",
    image: "https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=800&q=80",
    description: "Traditional Italian Gianduja blending 40% stone-ground IGP Piedmont hazelnuts with fine cocoa and delicate whole milk.",
    tastingNotes: ["Toasted Hazelnut", "Creamy Nougat", "Cocoa Butter", "Warm Cinnamon"],
    weight: "120g / 4.2 oz",
    dietary: ["Vegetarian", "Gluten-Free"],
    stock: 20,
    featured: false
  },

  // 4. TM White, Ruby & Exotic Delicacies
  {
    id: "tm-white-01",
    name: "TM Uji Kyoto Ceremonial Matcha White",
    category: "white",
    categoryLabel: "White & Ruby",
    price: 15.50,
    originalPrice: 18.50,
    rating: 4.9,
    reviewsCount: 164,
    cocoaPercentage: 34,
    origin: "Japan (Kyoto)",
    flag: "🇯🇵",
    badge: "Exotic Fusion",
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80",
    description: "Stone-ground first-harvest Uji matcha green tea infused into single-press organic cocoa butter with subtle vanilla orchid notes.",
    tastingNotes: ["Ceremonial Matcha", "Sweet Cream", "White Orchid", "Umami Sweetness"],
    weight: "90g / 3.2 oz",
    dietary: ["Vegetarian", "Organic"],
    stock: 16,
    featured: false
  },
  {
    id: "tm-white-02",
    name: "TM Ruby Berry Velvet Infusion",
    category: "white",
    categoryLabel: "White & Ruby",
    price: 14.00,
    originalPrice: 16.50,
    rating: 4.8,
    reviewsCount: 89,
    cocoaPercentage: 35,
    origin: "Belgium & Brazil",
    flag: "🇧🇪",
    badge: "Ruby Cacao",
    image: "https://images.unsplash.com/photo-1575372587186-5012e96fae57?auto=format&fit=crop&w=800&q=80",
    description: "Naturally vibrant pink ruby chocolate made from ruby cocoa beans, imparting luscious berry fruitiness without artificial flavors.",
    tastingNotes: ["Wild Strawberry", "Pomegranate", "Berry Tang", "Silky Cocoa"],
    weight: "90g / 3.2 oz",
    dietary: ["Vegetarian", "Gluten-Free"],
    stock: 22,
    featured: false
  },

  // 5. TM Truffles & Ganache
  {
    id: "tm-truffle-01",
    name: "TM Marc de Champagne Royal Truffles (12 Pcs)",
    category: "truffles",
    categoryLabel: "Truffles & Ganache",
    price: 28.00,
    originalPrice: 34.00,
    rating: 5.0,
    reviewsCount: 278,
    cocoaPercentage: 68,
    origin: "France (Épernay)",
    flag: "🇫🇷",
    badge: "Gold Medal",
    image: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80",
    description: "Dark chocolate shells brimming with whipped Marc de Champagne infused ganache, delicately dusted with powdered confectionery gold.",
    tastingNotes: ["Sparkling Champagne", "Whipped Cream", "Dark Cocoa", "White Pear"],
    weight: "180g / 6.3 oz",
    dietary: ["Vegetarian"],
    stock: 14,
    featured: true
  },
  {
    id: "tm-truffle-02",
    name: "TM Artisan Dark Ganache Truffle Box (16 Pcs)",
    category: "truffles",
    categoryLabel: "Truffles & Ganache",
    price: 32.00,
    originalPrice: 38.00,
    rating: 4.9,
    reviewsCount: 195,
    cocoaPercentage: 74,
    origin: "Belgium (Brussels)",
    flag: "🇧🇪",
    badge: "Boutique Choice",
    image: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&w=800&q=80",
    description: "Assortment of 4 origin ganaches: Venezuelan Tonka Bean, Ecuadorian Espresso, Smoked Sea Salt, and Cardamom Saffron Dark.",
    tastingNotes: ["Dark Ganache", "Tonka Bean", "Espresso", "Cardamom Saffron"],
    weight: "220g / 7.7 oz",
    dietary: ["Vegetarian", "Gluten-Free"],
    stock: 19,
    featured: true
  },

  // 6. TM Artisanal & Festive Gift Boxes
  {
    id: "tm-gift-01",
    name: "TM Royal Sweets & Cacao Tasting Vault (24 Pcs)",
    category: "gift-boxes",
    categoryLabel: "Artisanal Gift Boxes",
    price: 54.00,
    originalPrice: 65.00,
    rating: 5.0,
    reviewsCount: 420,
    cocoaPercentage: 70,
    origin: "TM Grand Selection",
    flag: "👑",
    badge: "TM Grand Signature",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
    description: "Our crowning jewel gift box bound in emerald velvet and embossed with TM 24K gold crest. Contains 24 premier royal sweets, single-origin bars & bonbons.",
    tastingNotes: ["Gold Kaju Katli", "Champagne Truffles", "Single-Terroir Bars", "Pistachio Rolls"],
    weight: "500g / 17.6 oz",
    dietary: ["Vegetarian", "Gourmet Selection", "Royal Gift"],
    stock: 15,
    featured: true
  },
  {
    id: "tm-gift-02",
    name: "TM Connoisseur Festive Hamper (12 Items)",
    category: "gift-boxes",
    categoryLabel: "Artisanal Gift Boxes",
    price: 68.00,
    originalPrice: 85.00,
    rating: 5.0,
    reviewsCount: 160,
    cocoaPercentage: 65,
    origin: "TM Boutique Hamper",
    flag: "🎁",
    badge: "Festive Special",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=800&q=80",
    description: "The ultimate luxury curation: 4 fusion sweet boxes, 4 origin chocolate bars, 2 truffle canisters, roasted spiced nuts, and brass tasting spoon.",
    tastingNotes: ["Festive Assortment", "Saffron Delicacies", "Dark Grand Crus", "Almond Pralines"],
    weight: "850g / 30 oz",
    dietary: ["Vegetarian", "Premium Luxury"],
    stock: 10,
    featured: true
  },

  // 7. TM Sugar-Free & Vegan Delights
  {
    id: "tm-vegan-01",
    name: "TM Keto 80% Monkfruit Cacao Dark",
    category: "vegan-keto",
    categoryLabel: "Sugar-Free & Vegan",
    price: 13.50,
    originalPrice: 15.00,
    rating: 4.7,
    reviewsCount: 95,
    cocoaPercentage: 80,
    origin: "Peru (San Martín)",
    flag: "🇵🇪",
    badge: "Zero Sugar",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    description: "Naturally sweetened with organic monkfruit extract. Zero refined sugar, 2g net carbs, rich in natural cacao polyphenols.",
    tastingNotes: ["Dark Roast", "Nutty Cacao", "Subtle Sweetness", "Cedar Wood"],
    weight: "85g / 3.0 oz",
    dietary: ["Vegan", "Sugar-Conscious", "Keto", "Gluten-Free"],
    stock: 30,
    featured: false
  },
  {
    id: "tm-vegan-02",
    name: "TM Oat Milk Sea Salt Caramel Bar (100% Plant-Based)",
    category: "vegan-keto",
    categoryLabel: "Sugar-Free & Vegan",
    price: 11.50,
    originalPrice: 13.00,
    rating: 4.8,
    reviewsCount: 138,
    cocoaPercentage: 50,
    origin: "United Kingdom",
    flag: "🇬🇧",
    badge: "100% Vegan",
    image: "https://images.unsplash.com/photo-1587132137056-bfbf0166836e?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-creamy oat milk chocolate paired with dairy-free coconut caramel and sea salt. Unbelievably rich and ethical.",
    tastingNotes: ["Creamy Oats", "Salted Coconut Caramel", "Vanilla", "Brown Sugar"],
    weight: "90g / 3.2 oz",
    dietary: ["Vegan", "Dairy-Free", "Organic"],
    stock: 26,
    featured: true
  }
];

// Available Currency conversion rates & symbols (Defaulting friendly to INR & USD)
const CURRENCIES = {
  INR: { symbol: "₹", rate: 86.50, label: "INR (₹)" },
  USD: { symbol: "$", rate: 1.00, label: "USD ($)" },
  EUR: { symbol: "€", rate: 0.92, label: "EUR (€)" },
  GBP: { symbol: "£", rate: 0.79, label: "GBP (£)" }
};

// Available Promo Codes
const PROMO_CODES = {
  "TMSWEETS": { type: "percent", value: 20, label: "20% TM Sweets Royal Welcome Discount" },
  "TM10": { type: "percent", value: 10, label: "10% Off Your Entire Order" },
  "LUXURY20": { type: "percent", value: 20, label: "20% Connoisseur VIP Discount" },
  "GOLDEN": { type: "fixed", value: 15.00, label: "$15.00 (₹1,300) Off Artisanal Gift Box" },
  "FREESHIP": { type: "shipping", value: 0, label: "Free Express Insulated Delivery" }
};
